apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    App: events-external
  name: events-external-deployment
  namespace: capstone-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      App: events-external
  strategy: {}
  template:
    metadata:
      labels:
        App: events-external
    spec:
      containers:
      - image: kenkool23/external-events:latest
        name: events-external
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-internal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
