pipeline {
  
  agent any
  
  environment {
      port = 8082
  }


  
  stages {
              
    stage('Git') {
      steps {
        git branch: 'main', url: 'https://github.com/kenkool23/capstone.git'
        echo 'cloning git repo'
      }
    }
     
    stage("Setting up npm"){
        steps {
            echo 'Installing npm' 
		     sh 'npm install'
             
            }
    }
    
    stage("Running the tests"){
        steps {
            echo 'Installing npm' 
		    //sh 'npm test'
        }
    }

    

    stage("Build Docker image"){
        steps{
                echo 'Building Docker image' 
                sh 'gcloud builds submit -t gcr.io/capstone-project-308119/external-micro:${BUILD_ID} external-micro'
                echo 'Done' 
            }
          }

    
    stage("Connecting to the cluster"){
        steps {
            echo 'Connecting to the cluster' 
		
		    sh 'gcloud container clusters get-credentials capstone --zone us-central1-c --project capstone-project-308119'
        }
    }
    
    
    stage("Deploying the image"){
        steps {
            echo 'Setting the image' 
		
		    sh 'kubectl set image gcr.io/mar-roidtc307/devoops_internal:latest --record'
		    sh 'kubectl set image gcr.io/capstone-project-308119/external-micro nginx=external-micro:$(BUILD_ID) --record'
        }
    }
    
    
  }

}