pipeline {
  
  agent any
  
  environment {
      port = 8082
  }


  
  stages {
              
    stage('Git') {
      steps {
        git 'https://github.com/kenkool23/capstone/tree/main/external-micro'
        sh 'cloning git repo'
      }
    }
     
    stage("Setting up npm"){
        steps {
            echo 'Installing npm' 
		
		    sh 'npm install'
             
            }
    }
    
    stage("Running the tests"){
        steps {
            echo 'Installing npm' 
		
		    sh 'npm test'
        }
    }

    

    stage("Build Docker image"){
        steps{
                echo 'Building Docker image' 
                sh 'gcloud builds submit -t gcr.io/mar-roidtc307/devoops_external:latest .'
                echo 'Done' 
            }
          }

    
    stage("Connecting to the cluster"){
        steps {
            echo 'Connecting to the cluster' 
		
		    sh 'gcloud container clusters get-credentials devsoops --zone us-central1-a --project mar-roidtc307'
        }
    }
    
    
    stage("Deploying the image"){
        steps {
            echo 'Setting the image' 
		
		    //sh 'kubectl set image gcr.io/mar-roidtc307/devoops_internal:latest --record'
		    sh 'kubectl apply -f external-deployment.yaml'
        }
    }
    
    

  }

}